trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ado

steps:
- checkout: self

- script: |
    echo "Initializing Terraform..."
    terraform init \
      -backend-config="resource_group_name=$(backend_resource_group_name)" \
      -backend-config="storage_account_name=$(backend_storage_account_name)" \
      -backend-config="container_name=$(backend_container_name)" \
      -backend-config="key=$(backend_statefile_key)" \
      -backend-config="access_key=$(backend_access_key)"
    echo "Running Terraform plan..."
    terraform plan -var "personal_access_token=$(personal_access_token)" -out=tfplan
    echo "Applying Terraform configuration..."
    terraform apply -auto-approve tfplan
  displayName: 'Initialize and Apply Terraform'
  env:
    TF_VAR_personal_access_token: $(personal_access_token)
    TF_VAR_org_service_url: $(org_service_url)

